language: python
python:
    - "3.10"
    - "3.9"
    - "3.8"
    - "3.7"
    - "3.6"
    - "3.5"
    - "3.4"
    - "pypy"

install:
  - pip install .
  - pip install -r test_requirements.txt

script:
  - nosetests --with-cover --cover-branches --cover-package=memoize

after_success:
  - coveralls
